package mapbrowser.api;

import arc.struct.*;
import arc.util.serialization.*;
import arc.util.serialization.Json.*;
import mindustry.game.*;

// Generated by AI
public class BackendTypes{
    public static class SiteMapInfo{
        public int id;
        public String name;
        public String desc;
        public String preview;
        public Seq<String> tags;
    }

    public static class SiteMapDetails{
        public int thread;
        public String mode;
        public String preview;
        public SiteUserInfo user;
        public SiteMapTags tags;

        public static class SiteUserInfo{
            public String name;
            public String gid;
        }
    }

    public static class SiteMapTags implements JsonSerializable{
        public String name;
        public String author;
        public String description;
        public int width;
        public int height;
        public Seq<String> mods;
        public SiteMapRules rules;
//        public int wave;
//        public int build;
//        public int saved;
//        public Object stats;
//        public String viewpos;
//        public int playtime;
//        public int wavetime;
//        public int saveVersion;
//        public String controlledType;
//        public Seq<Object> genfilters;

        @Override
        public void write(Json json){
            json.writeValue(this);
        }

        @Override
        public void read(Json json, JsonValue jsonData){
            // maybe string
            JsonValue rulesJson = jsonData.get("rules");
            if(rulesJson.isString()){
                jsonData.remove("rules");
                rules = json.fromJson(SiteMapRules.class, rulesJson.asString());
            }

            json.readFields(this, jsonData);
            jsonData.addChild("rules", rulesJson);
        }
    }

    public enum SiteGameMode{
        Survive(Gamemode.survival),
        Pvp(Gamemode.survival),
        Attack(Gamemode.attack),
        Sandbox(Gamemode.sandbox),
        Editor(Gamemode.editor),
        UnKnown(null);

        public final Gamemode mode;

        SiteGameMode(Gamemode mode){
            this.mode = mode;
        }
    }

    public static class SiteMapRules{
        public boolean waves;
        public boolean unitAmmo;
        public boolean damageExplosions;
        public boolean reactorExplosions;
        public boolean attackMode;
        public boolean fire;
        public boolean unitCapVariable;

        public float waveSpacing;
        public float dropZoneRadius;
        public float enemyCoreBuildRadius;

        public float buildCostMultiplier;
        public float buildSpeedMultiplier;
        public float unitDamageMultiplier;
        public float blockDamageMultiplier;
        public float blockHealthMultiplier;
        public float unitBuildSpeedMultiplier;
        public float deconstructRefundMultiplier;
        public float solarPowerMultiplier;

        public int unitCap;
        public SiteMapContents bannedBlocks;
        public SiteMapContents bannedUnits;
        public SiteMapContents revealedBlocks;

        public Seq<SpawnGroup> spawns;
//        public ObjectMap<String, SiteTeamRules> teams;
//        public Seq<SiteLoadout> loadout;
    }

    public static class SiteMapContents{
        public Seq<String> values;
    }

    public static class SiteLoadout{
        public String item;
        public int amount;
    }

    public static class SiteTeamRules{
        public boolean infiniteAmmo;
    }
}
